using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.UI;
using System.Web.UI.WebControls;
using umbraco.interfaces;

namespace Zbu.DataTypes.RepeatableFragment
{
    class RepeatableFragmentEditor : PlaceHolder, IDataEditor
    {
        private readonly IData _data;
        private readonly RepeatableFragmentPrevalueEditor.ConfigData _config;

        private TextBox _text; // TEMP

        // FIXME
        // _text should be _jsonData, a hidden field containing the json generated by the UI

        public RepeatableFragmentEditor(IData data, RepeatableFragmentPrevalueEditor.ConfigData config)
        {
            _data = data;
            _config = config;
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);

            var panel = new Panel();

            _text = new TextBox
            {
                ID = ID + "_text"
            };

            var data = _data.Value as string;
            _text.Text = data;
            panel.Controls.Add(_text);

            var lit = new Literal
            {
                Text = "**" + _config.FragmentTypeAlias + "**"
            };
            panel.Controls.Add(lit);

            Controls.Add(panel);
        }

        public Control Editor
        {
            get { return this; }
        }

        public void Save()
        {
            var data = _text.Text;
            _data.Value = data;
        }

        public bool ShowLabel
        {
            get { return true; }
        }

        public bool TreatAsRichTextEditor
        {
            get { return false; }
        }
    }
}
