using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Cache;
using System.Text;
using System.Threading.Tasks;
using System.Web.UI;
using System.Web.UI.WebControls;
using Umbraco.Core.IO;
using umbraco.interfaces;
using umbraco.editorControls;

[assembly: WebResource("Zbu.DataTypes.RepeatableFragment.RepeatableFragment.css", "text/css")]
[assembly: WebResource("Zbu.DataTypes.RepeatableFragment.RepeatableFragment.js", "application/x-javascript")]

namespace Zbu.DataTypes.RepeatableFragment
{
    class RepeatableFragmentEditor : PlaceHolder, IDataEditor
    {
        private readonly IData _data;
        private readonly RepeatableFragmentPrevalueEditor.ConfigData _config;

        private TextBox /*HiddenField*/ _formData;

        // FIXME
        // _text should be _jsonData, a hidden field containing the json generated by the UI

        public RepeatableFragmentEditor(IData data, RepeatableFragmentPrevalueEditor.ConfigData config)
        {
            _data = data;
            _config = config;
        }

        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);

            var panel = new Panel();
            panel.ID = ID + "_edit";

            _formData = new TextBox //HiddenField
            {
                ID = ID + "_data"
            };
            var data = _data.Value as string;
            if (string.IsNullOrWhiteSpace(data))
            {
                var fragment = new Fragment
                {
                    FragmentTypeAlias = _config.FragmentTypeAlias
                };
                var serializer = new JsonSerializer();
                data = serializer.Serialize(fragment);
            }
            _formData.Text = data;
            panel.Controls.Add(_formData);

            var contentId = Page.Request.QueryString["id"];

            var html = @"
<div class=""zbu-repeatable-fragment-div"">test</div>
<a href=""#"" id=""{0}_add"">add</a>
<script type=""text/javascript"">
    $('#{0}_edit').zbu('repeatable-fragment', {{
        umbraco: '{1}',
        contentId: {2}
    }});
</script>
";

            panel.Controls.Add(new LiteralControl(string.Format(html,
                ClientID,
                IOHelper.ResolveUrl(SystemDirectories.Umbraco).Replace("'", "\\'"),
                //_config.FragmentTypeAlias.Replace("'", "\\'"),
                contentId)));

            Controls.Add(panel);
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);

            // register our resources
            this.RegisterEmbeddedClientResource("Zbu.DataTypes.RepeatableFragment.RepeatableFragment.css",
                umbraco.cms.businesslogic.datatype.ClientDependencyType.Css);
            this.RegisterEmbeddedClientResource("Zbu.DataTypes.RepeatableFragment.RepeatableFragment.js",
                umbraco.cms.businesslogic.datatype.ClientDependencyType.Javascript);
        }

        public Control Editor
        {
            get { return this; }
        }

        public void Save()
        {
            var data = _formData.Text;
            _data.Value = data;
        }

        public bool ShowLabel
        {
            get { return true; }
        }

        public bool TreatAsRichTextEditor
        {
            get { return false; }
        }
    }
}
